export const SIGNUP_POST_API_V1_SIGNUP_READ = "SIGNUP_POST_API_V1_SIGNUP_READ"
export const SIGNUP_POST_API_V1_SIGNUP_READ_SUCCEEDED =
  "SIGNUP_POST_API_V1_SIGNUP_READ_SUCCEEDED"
export const SIGNUP_POST_API_V1_SIGNUP_READ_FAILED =
  "SIGNUP_POST_API_V1_SIGNUP_READ_FAILED"
export const API_V1_BILL_LIST = "API_V1_BILL_LIST"
export const API_V1_BILL_LIST_SUCCEEDED = "API_V1_BILL_LIST_SUCCEEDED"
export const API_V1_BILL_LIST_FAILED = "API_V1_BILL_LIST_FAILED"
export const API_V1_BILL_CREATE = "API_V1_BILL_CREATE"
export const API_V1_BILL_CREATE_SUCCEEDED = "API_V1_BILL_CREATE_SUCCEEDED"
export const API_V1_BILL_CREATE_FAILED = "API_V1_BILL_CREATE_FAILED"
export const API_V1_BILL_READ = "API_V1_BILL_READ"
export const API_V1_BILL_READ_SUCCEEDED = "API_V1_BILL_READ_SUCCEEDED"
export const API_V1_BILL_READ_FAILED = "API_V1_BILL_READ_FAILED"
export const API_V1_BILL_UPDATE = "API_V1_BILL_UPDATE"
export const API_V1_BILL_UPDATE_SUCCEEDED = "API_V1_BILL_UPDATE_SUCCEEDED"
export const API_V1_BILL_UPDATE_FAILED = "API_V1_BILL_UPDATE_FAILED"
export const API_V1_BILL_PARTIAL_UPDATE = "API_V1_BILL_PARTIAL_UPDATE"
export const API_V1_BILL_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_BILL_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_BILL_PARTIAL_UPDATE_FAILED =
  "API_V1_BILL_PARTIAL_UPDATE_FAILED"
export const API_V1_BILL_DELETE = "API_V1_BILL_DELETE"
export const API_V1_BILL_DELETE_SUCCEEDED = "API_V1_BILL_DELETE_SUCCEEDED"
export const API_V1_BILL_DELETE_FAILED = "API_V1_BILL_DELETE_FAILED"
export const API_V1_CATEGORY_LIST = "API_V1_CATEGORY_LIST"
export const API_V1_CATEGORY_LIST_SUCCEEDED = "API_V1_CATEGORY_LIST_SUCCEEDED"
export const API_V1_CATEGORY_LIST_FAILED = "API_V1_CATEGORY_LIST_FAILED"
export const API_V1_CATEGORY_CREATE = "API_V1_CATEGORY_CREATE"
export const API_V1_CATEGORY_CREATE_SUCCEEDED =
  "API_V1_CATEGORY_CREATE_SUCCEEDED"
export const API_V1_CATEGORY_CREATE_FAILED = "API_V1_CATEGORY_CREATE_FAILED"
export const API_V1_CATEGORY_READ = "API_V1_CATEGORY_READ"
export const API_V1_CATEGORY_READ_SUCCEEDED = "API_V1_CATEGORY_READ_SUCCEEDED"
export const API_V1_CATEGORY_READ_FAILED = "API_V1_CATEGORY_READ_FAILED"
export const API_V1_CATEGORY_UPDATE = "API_V1_CATEGORY_UPDATE"
export const API_V1_CATEGORY_UPDATE_SUCCEEDED =
  "API_V1_CATEGORY_UPDATE_SUCCEEDED"
export const API_V1_CATEGORY_UPDATE_FAILED = "API_V1_CATEGORY_UPDATE_FAILED"
export const API_V1_CATEGORY_PARTIAL_UPDATE = "API_V1_CATEGORY_PARTIAL_UPDATE"
export const API_V1_CATEGORY_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CATEGORY_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CATEGORY_PARTIAL_UPDATE_FAILED =
  "API_V1_CATEGORY_PARTIAL_UPDATE_FAILED"
export const API_V1_CATEGORY_DELETE = "API_V1_CATEGORY_DELETE"
export const API_V1_CATEGORY_DELETE_SUCCEEDED =
  "API_V1_CATEGORY_DELETE_SUCCEEDED"
export const API_V1_CATEGORY_DELETE_FAILED = "API_V1_CATEGORY_DELETE_FAILED"
export const API_V1_CONTACTINFO_LIST = "API_V1_CONTACTINFO_LIST"
export const API_V1_CONTACTINFO_LIST_SUCCEEDED =
  "API_V1_CONTACTINFO_LIST_SUCCEEDED"
export const API_V1_CONTACTINFO_LIST_FAILED = "API_V1_CONTACTINFO_LIST_FAILED"
export const API_V1_CONTACTINFO_CREATE = "API_V1_CONTACTINFO_CREATE"
export const API_V1_CONTACTINFO_CREATE_SUCCEEDED =
  "API_V1_CONTACTINFO_CREATE_SUCCEEDED"
export const API_V1_CONTACTINFO_CREATE_FAILED =
  "API_V1_CONTACTINFO_CREATE_FAILED"
export const API_V1_CONTACTINFO_READ = "API_V1_CONTACTINFO_READ"
export const API_V1_CONTACTINFO_READ_SUCCEEDED =
  "API_V1_CONTACTINFO_READ_SUCCEEDED"
export const API_V1_CONTACTINFO_READ_FAILED = "API_V1_CONTACTINFO_READ_FAILED"
export const API_V1_CONTACTINFO_UPDATE = "API_V1_CONTACTINFO_UPDATE"
export const API_V1_CONTACTINFO_UPDATE_SUCCEEDED =
  "API_V1_CONTACTINFO_UPDATE_SUCCEEDED"
export const API_V1_CONTACTINFO_UPDATE_FAILED =
  "API_V1_CONTACTINFO_UPDATE_FAILED"
export const API_V1_CONTACTINFO_PARTIAL_UPDATE =
  "API_V1_CONTACTINFO_PARTIAL_UPDATE"
export const API_V1_CONTACTINFO_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CONTACTINFO_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CONTACTINFO_PARTIAL_UPDATE_FAILED =
  "API_V1_CONTACTINFO_PARTIAL_UPDATE_FAILED"
export const API_V1_CONTACTINFO_DELETE = "API_V1_CONTACTINFO_DELETE"
export const API_V1_CONTACTINFO_DELETE_SUCCEEDED =
  "API_V1_CONTACTINFO_DELETE_SUCCEEDED"
export const API_V1_CONTACTINFO_DELETE_FAILED =
  "API_V1_CONTACTINFO_DELETE_FAILED"
export const API_V1_COUNTRY_LIST = "API_V1_COUNTRY_LIST"
export const API_V1_COUNTRY_LIST_SUCCEEDED = "API_V1_COUNTRY_LIST_SUCCEEDED"
export const API_V1_COUNTRY_LIST_FAILED = "API_V1_COUNTRY_LIST_FAILED"
export const API_V1_COUNTRY_CREATE = "API_V1_COUNTRY_CREATE"
export const API_V1_COUNTRY_CREATE_SUCCEEDED = "API_V1_COUNTRY_CREATE_SUCCEEDED"
export const API_V1_COUNTRY_CREATE_FAILED = "API_V1_COUNTRY_CREATE_FAILED"
export const API_V1_COUNTRY_READ = "API_V1_COUNTRY_READ"
export const API_V1_COUNTRY_READ_SUCCEEDED = "API_V1_COUNTRY_READ_SUCCEEDED"
export const API_V1_COUNTRY_READ_FAILED = "API_V1_COUNTRY_READ_FAILED"
export const API_V1_COUNTRY_UPDATE = "API_V1_COUNTRY_UPDATE"
export const API_V1_COUNTRY_UPDATE_SUCCEEDED = "API_V1_COUNTRY_UPDATE_SUCCEEDED"
export const API_V1_COUNTRY_UPDATE_FAILED = "API_V1_COUNTRY_UPDATE_FAILED"
export const API_V1_COUNTRY_PARTIAL_UPDATE = "API_V1_COUNTRY_PARTIAL_UPDATE"
export const API_V1_COUNTRY_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_COUNTRY_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_COUNTRY_PARTIAL_UPDATE_FAILED =
  "API_V1_COUNTRY_PARTIAL_UPDATE_FAILED"
export const API_V1_COUNTRY_DELETE = "API_V1_COUNTRY_DELETE"
export const API_V1_COUNTRY_DELETE_SUCCEEDED = "API_V1_COUNTRY_DELETE_SUCCEEDED"
export const API_V1_COUNTRY_DELETE_FAILED = "API_V1_COUNTRY_DELETE_FAILED"
export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_DRIVERORDER_LIST = "API_V1_DRIVERORDER_LIST"
export const API_V1_DRIVERORDER_LIST_SUCCEEDED =
  "API_V1_DRIVERORDER_LIST_SUCCEEDED"
export const API_V1_DRIVERORDER_LIST_FAILED = "API_V1_DRIVERORDER_LIST_FAILED"
export const API_V1_DRIVERORDER_CREATE = "API_V1_DRIVERORDER_CREATE"
export const API_V1_DRIVERORDER_CREATE_SUCCEEDED =
  "API_V1_DRIVERORDER_CREATE_SUCCEEDED"
export const API_V1_DRIVERORDER_CREATE_FAILED =
  "API_V1_DRIVERORDER_CREATE_FAILED"
export const API_V1_DRIVERORDER_READ = "API_V1_DRIVERORDER_READ"
export const API_V1_DRIVERORDER_READ_SUCCEEDED =
  "API_V1_DRIVERORDER_READ_SUCCEEDED"
export const API_V1_DRIVERORDER_READ_FAILED = "API_V1_DRIVERORDER_READ_FAILED"
export const API_V1_DRIVERORDER_UPDATE = "API_V1_DRIVERORDER_UPDATE"
export const API_V1_DRIVERORDER_UPDATE_SUCCEEDED =
  "API_V1_DRIVERORDER_UPDATE_SUCCEEDED"
export const API_V1_DRIVERORDER_UPDATE_FAILED =
  "API_V1_DRIVERORDER_UPDATE_FAILED"
export const API_V1_DRIVERORDER_PARTIAL_UPDATE =
  "API_V1_DRIVERORDER_PARTIAL_UPDATE"
export const API_V1_DRIVERORDER_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_DRIVERORDER_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_DRIVERORDER_PARTIAL_UPDATE_FAILED =
  "API_V1_DRIVERORDER_PARTIAL_UPDATE_FAILED"
export const API_V1_DRIVERORDER_DELETE = "API_V1_DRIVERORDER_DELETE"
export const API_V1_DRIVERORDER_DELETE_SUCCEEDED =
  "API_V1_DRIVERORDER_DELETE_SUCCEEDED"
export const API_V1_DRIVERORDER_DELETE_FAILED =
  "API_V1_DRIVERORDER_DELETE_FAILED"
export const API_V1_DRIVERPROFILE_LIST = "API_V1_DRIVERPROFILE_LIST"
export const API_V1_DRIVERPROFILE_LIST_SUCCEEDED =
  "API_V1_DRIVERPROFILE_LIST_SUCCEEDED"
export const API_V1_DRIVERPROFILE_LIST_FAILED =
  "API_V1_DRIVERPROFILE_LIST_FAILED"
export const API_V1_DRIVERPROFILE_CREATE = "API_V1_DRIVERPROFILE_CREATE"
export const API_V1_DRIVERPROFILE_CREATE_SUCCEEDED =
  "API_V1_DRIVERPROFILE_CREATE_SUCCEEDED"
export const API_V1_DRIVERPROFILE_CREATE_FAILED =
  "API_V1_DRIVERPROFILE_CREATE_FAILED"
export const API_V1_DRIVERPROFILE_READ = "API_V1_DRIVERPROFILE_READ"
export const API_V1_DRIVERPROFILE_READ_SUCCEEDED =
  "API_V1_DRIVERPROFILE_READ_SUCCEEDED"
export const API_V1_DRIVERPROFILE_READ_FAILED =
  "API_V1_DRIVERPROFILE_READ_FAILED"
export const API_V1_DRIVERPROFILE_UPDATE = "API_V1_DRIVERPROFILE_UPDATE"
export const API_V1_DRIVERPROFILE_UPDATE_SUCCEEDED =
  "API_V1_DRIVERPROFILE_UPDATE_SUCCEEDED"
export const API_V1_DRIVERPROFILE_UPDATE_FAILED =
  "API_V1_DRIVERPROFILE_UPDATE_FAILED"
export const API_V1_DRIVERPROFILE_PARTIAL_UPDATE =
  "API_V1_DRIVERPROFILE_PARTIAL_UPDATE"
export const API_V1_DRIVERPROFILE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_DRIVERPROFILE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_DRIVERPROFILE_PARTIAL_UPDATE_FAILED =
  "API_V1_DRIVERPROFILE_PARTIAL_UPDATE_FAILED"
export const API_V1_DRIVERPROFILE_DELETE = "API_V1_DRIVERPROFILE_DELETE"
export const API_V1_DRIVERPROFILE_DELETE_SUCCEEDED =
  "API_V1_DRIVERPROFILE_DELETE_SUCCEEDED"
export const API_V1_DRIVERPROFILE_DELETE_FAILED =
  "API_V1_DRIVERPROFILE_DELETE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_ITEM_LIST = "API_V1_ITEM_LIST"
export const API_V1_ITEM_LIST_SUCCEEDED = "API_V1_ITEM_LIST_SUCCEEDED"
export const API_V1_ITEM_LIST_FAILED = "API_V1_ITEM_LIST_FAILED"
export const API_V1_ITEM_CREATE = "API_V1_ITEM_CREATE"
export const API_V1_ITEM_CREATE_SUCCEEDED = "API_V1_ITEM_CREATE_SUCCEEDED"
export const API_V1_ITEM_CREATE_FAILED = "API_V1_ITEM_CREATE_FAILED"
export const API_V1_ITEM_READ = "API_V1_ITEM_READ"
export const API_V1_ITEM_READ_SUCCEEDED = "API_V1_ITEM_READ_SUCCEEDED"
export const API_V1_ITEM_READ_FAILED = "API_V1_ITEM_READ_FAILED"
export const API_V1_ITEM_UPDATE = "API_V1_ITEM_UPDATE"
export const API_V1_ITEM_UPDATE_SUCCEEDED = "API_V1_ITEM_UPDATE_SUCCEEDED"
export const API_V1_ITEM_UPDATE_FAILED = "API_V1_ITEM_UPDATE_FAILED"
export const API_V1_ITEM_PARTIAL_UPDATE = "API_V1_ITEM_PARTIAL_UPDATE"
export const API_V1_ITEM_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_ITEM_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_ITEM_PARTIAL_UPDATE_FAILED =
  "API_V1_ITEM_PARTIAL_UPDATE_FAILED"
export const API_V1_ITEM_DELETE = "API_V1_ITEM_DELETE"
export const API_V1_ITEM_DELETE_SUCCEEDED = "API_V1_ITEM_DELETE_SUCCEEDED"
export const API_V1_ITEM_DELETE_FAILED = "API_V1_ITEM_DELETE_FAILED"
export const API_V1_ITEMVARIANT_LIST = "API_V1_ITEMVARIANT_LIST"
export const API_V1_ITEMVARIANT_LIST_SUCCEEDED =
  "API_V1_ITEMVARIANT_LIST_SUCCEEDED"
export const API_V1_ITEMVARIANT_LIST_FAILED = "API_V1_ITEMVARIANT_LIST_FAILED"
export const API_V1_ITEMVARIANT_CREATE = "API_V1_ITEMVARIANT_CREATE"
export const API_V1_ITEMVARIANT_CREATE_SUCCEEDED =
  "API_V1_ITEMVARIANT_CREATE_SUCCEEDED"
export const API_V1_ITEMVARIANT_CREATE_FAILED =
  "API_V1_ITEMVARIANT_CREATE_FAILED"
export const API_V1_ITEMVARIANT_READ = "API_V1_ITEMVARIANT_READ"
export const API_V1_ITEMVARIANT_READ_SUCCEEDED =
  "API_V1_ITEMVARIANT_READ_SUCCEEDED"
export const API_V1_ITEMVARIANT_READ_FAILED = "API_V1_ITEMVARIANT_READ_FAILED"
export const API_V1_ITEMVARIANT_UPDATE = "API_V1_ITEMVARIANT_UPDATE"
export const API_V1_ITEMVARIANT_UPDATE_SUCCEEDED =
  "API_V1_ITEMVARIANT_UPDATE_SUCCEEDED"
export const API_V1_ITEMVARIANT_UPDATE_FAILED =
  "API_V1_ITEMVARIANT_UPDATE_FAILED"
export const API_V1_ITEMVARIANT_PARTIAL_UPDATE =
  "API_V1_ITEMVARIANT_PARTIAL_UPDATE"
export const API_V1_ITEMVARIANT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_ITEMVARIANT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_ITEMVARIANT_PARTIAL_UPDATE_FAILED =
  "API_V1_ITEMVARIANT_PARTIAL_UPDATE_FAILED"
export const API_V1_ITEMVARIANT_DELETE = "API_V1_ITEMVARIANT_DELETE"
export const API_V1_ITEMVARIANT_DELETE_SUCCEEDED =
  "API_V1_ITEMVARIANT_DELETE_SUCCEEDED"
export const API_V1_ITEMVARIANT_DELETE_FAILED =
  "API_V1_ITEMVARIANT_DELETE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_ORDER_LIST = "API_V1_ORDER_LIST"
export const API_V1_ORDER_LIST_SUCCEEDED = "API_V1_ORDER_LIST_SUCCEEDED"
export const API_V1_ORDER_LIST_FAILED = "API_V1_ORDER_LIST_FAILED"
export const API_V1_ORDER_CREATE = "API_V1_ORDER_CREATE"
export const API_V1_ORDER_CREATE_SUCCEEDED = "API_V1_ORDER_CREATE_SUCCEEDED"
export const API_V1_ORDER_CREATE_FAILED = "API_V1_ORDER_CREATE_FAILED"
export const API_V1_ORDER_READ = "API_V1_ORDER_READ"
export const API_V1_ORDER_READ_SUCCEEDED = "API_V1_ORDER_READ_SUCCEEDED"
export const API_V1_ORDER_READ_FAILED = "API_V1_ORDER_READ_FAILED"
export const API_V1_ORDER_UPDATE = "API_V1_ORDER_UPDATE"
export const API_V1_ORDER_UPDATE_SUCCEEDED = "API_V1_ORDER_UPDATE_SUCCEEDED"
export const API_V1_ORDER_UPDATE_FAILED = "API_V1_ORDER_UPDATE_FAILED"
export const API_V1_ORDER_PARTIAL_UPDATE = "API_V1_ORDER_PARTIAL_UPDATE"
export const API_V1_ORDER_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_ORDER_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_ORDER_PARTIAL_UPDATE_FAILED =
  "API_V1_ORDER_PARTIAL_UPDATE_FAILED"
export const API_V1_ORDER_DELETE = "API_V1_ORDER_DELETE"
export const API_V1_ORDER_DELETE_SUCCEEDED = "API_V1_ORDER_DELETE_SUCCEEDED"
export const API_V1_ORDER_DELETE_FAILED = "API_V1_ORDER_DELETE_FAILED"
export const API_V1_PAYMENTMETHOD_LIST = "API_V1_PAYMENTMETHOD_LIST"
export const API_V1_PAYMENTMETHOD_LIST_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_LIST_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_LIST_FAILED =
  "API_V1_PAYMENTMETHOD_LIST_FAILED"
export const API_V1_PAYMENTMETHOD_CREATE = "API_V1_PAYMENTMETHOD_CREATE"
export const API_V1_PAYMENTMETHOD_CREATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_CREATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_CREATE_FAILED =
  "API_V1_PAYMENTMETHOD_CREATE_FAILED"
export const API_V1_PAYMENTMETHOD_READ = "API_V1_PAYMENTMETHOD_READ"
export const API_V1_PAYMENTMETHOD_READ_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_READ_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_READ_FAILED =
  "API_V1_PAYMENTMETHOD_READ_FAILED"
export const API_V1_PAYMENTMETHOD_UPDATE = "API_V1_PAYMENTMETHOD_UPDATE"
export const API_V1_PAYMENTMETHOD_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_UPDATE_FAILED =
  "API_V1_PAYMENTMETHOD_UPDATE_FAILED"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_FAILED =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_FAILED"
export const API_V1_PAYMENTMETHOD_DELETE = "API_V1_PAYMENTMETHOD_DELETE"
export const API_V1_PAYMENTMETHOD_DELETE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_DELETE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_DELETE_FAILED =
  "API_V1_PAYMENTMETHOD_DELETE_FAILED"
export const API_V1_PROFILE_LIST = "API_V1_PROFILE_LIST"
export const API_V1_PROFILE_LIST_SUCCEEDED = "API_V1_PROFILE_LIST_SUCCEEDED"
export const API_V1_PROFILE_LIST_FAILED = "API_V1_PROFILE_LIST_FAILED"
export const API_V1_PROFILE_CREATE = "API_V1_PROFILE_CREATE"
export const API_V1_PROFILE_CREATE_SUCCEEDED = "API_V1_PROFILE_CREATE_SUCCEEDED"
export const API_V1_PROFILE_CREATE_FAILED = "API_V1_PROFILE_CREATE_FAILED"
export const API_V1_PROFILE_READ = "API_V1_PROFILE_READ"
export const API_V1_PROFILE_READ_SUCCEEDED = "API_V1_PROFILE_READ_SUCCEEDED"
export const API_V1_PROFILE_READ_FAILED = "API_V1_PROFILE_READ_FAILED"
export const API_V1_PROFILE_UPDATE = "API_V1_PROFILE_UPDATE"
export const API_V1_PROFILE_UPDATE_SUCCEEDED = "API_V1_PROFILE_UPDATE_SUCCEEDED"
export const API_V1_PROFILE_UPDATE_FAILED = "API_V1_PROFILE_UPDATE_FAILED"
export const API_V1_PROFILE_PARTIAL_UPDATE = "API_V1_PROFILE_PARTIAL_UPDATE"
export const API_V1_PROFILE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PROFILE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PROFILE_PARTIAL_UPDATE_FAILED =
  "API_V1_PROFILE_PARTIAL_UPDATE_FAILED"
export const API_V1_PROFILE_DELETE = "API_V1_PROFILE_DELETE"
export const API_V1_PROFILE_DELETE_SUCCEEDED = "API_V1_PROFILE_DELETE_SUCCEEDED"
export const API_V1_PROFILE_DELETE_FAILED = "API_V1_PROFILE_DELETE_FAILED"
export const API_V1_REVIEW_LIST = "API_V1_REVIEW_LIST"
export const API_V1_REVIEW_LIST_SUCCEEDED = "API_V1_REVIEW_LIST_SUCCEEDED"
export const API_V1_REVIEW_LIST_FAILED = "API_V1_REVIEW_LIST_FAILED"
export const API_V1_REVIEW_CREATE = "API_V1_REVIEW_CREATE"
export const API_V1_REVIEW_CREATE_SUCCEEDED = "API_V1_REVIEW_CREATE_SUCCEEDED"
export const API_V1_REVIEW_CREATE_FAILED = "API_V1_REVIEW_CREATE_FAILED"
export const API_V1_REVIEW_READ = "API_V1_REVIEW_READ"
export const API_V1_REVIEW_READ_SUCCEEDED = "API_V1_REVIEW_READ_SUCCEEDED"
export const API_V1_REVIEW_READ_FAILED = "API_V1_REVIEW_READ_FAILED"
export const API_V1_REVIEW_UPDATE = "API_V1_REVIEW_UPDATE"
export const API_V1_REVIEW_UPDATE_SUCCEEDED = "API_V1_REVIEW_UPDATE_SUCCEEDED"
export const API_V1_REVIEW_UPDATE_FAILED = "API_V1_REVIEW_UPDATE_FAILED"
export const API_V1_REVIEW_PARTIAL_UPDATE = "API_V1_REVIEW_PARTIAL_UPDATE"
export const API_V1_REVIEW_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_REVIEW_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_REVIEW_PARTIAL_UPDATE_FAILED =
  "API_V1_REVIEW_PARTIAL_UPDATE_FAILED"
export const API_V1_REVIEW_DELETE = "API_V1_REVIEW_DELETE"
export const API_V1_REVIEW_DELETE_SUCCEEDED = "API_V1_REVIEW_DELETE_SUCCEEDED"
export const API_V1_REVIEW_DELETE_FAILED = "API_V1_REVIEW_DELETE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
